excluded:
  - .build
  - DerivedData
  - iToneUITests

disabled_rules:
  - todo
  - trailing_comma

type_name:
  excluded:
    - iToneApp
    - iTunesAPI
    - iTunesSearchResponse
    - iTunesTrackDTO
    - iToneModelContainer
